package com.marketingagent.domain.audit;

public enum AuditActionType {
    CONTACT_IMPORT_CREATED,
    CONSENT_RECORDED,
    TEMPLATE_SUBMITTED,
    CAMPAIGN_APPROVED,
    CAMPAIGN_REJECTED,
    BROADCAST_STARTED,
    BROADCAST_PAUSED,
    BROADCAST_CANCELED,
    DATA_EXPORTED,
    ADMIN_ACTION,
    PDF_EXTRACTION_STARTED,
    PDF_EXTRACTION_SUCCESS,
    PDF_EXTRACTION_FAILED,
    WHATSAPP_MESSAGE_SENT,
    WHATSAPP_MESSAGE_FAILED
}
